# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  rsync:
    runs-on: ubuntu-latest
    steps:
      # Must checkout first, otherwise would get empty folder, see https://github.com/actions/checkout
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
      # Modify `master` to valid version, from https://github.com/marketplace/actions/action-rsync
      - name: 🚀 RSYNC Deploy
        uses: up9cloud/action-rsync@master
        env:
          HOST: srv.plopcom.fr
          USER : ${{secrets.DEPLOY_SSH_USER}}
          KEY: ${{secrets.DEPLOY_SSH_KEY}}
          PORT: ${{secrets.DEPLOY_SSH_PORT}}
          TARGET: ${{secrets.DEPLOY_SSH_TARGET}}
          PRE_SCRIPT: "echo start at: && date -u"
          POST_SCRIPT: "echo done at: && date -u"
